name: ${name}
version: ${version}
description: ${description}
authors: [Gecolay]
website: https://www.spigotmc.org/resources/84004
main: ${main}
api-version: 1.18
folia-supported: true
softdepend: [GriefPrevention, PlaceholderAPI, PlotSquared, WorldGuard]

commands:
  gmusic:
    usage: /<command> [play|playing|random|stop|pause|resume|skip|toggle]
    aliases: [music, gsong, song]
    description: Music command
    permission: GMusic.Music

  gadminmusic:
    usage: /<command> [jukebox|disc|download|radio|play|playing|random|stop|pause|resume|skip|toggle]
    aliases: [adminmusic, gamusic, amusic, gadminsong, adminsong, gasong, asong]
    description: AMusic command
    permission: GMusic.AdminMusic

  gmusicreload:
    usage: /<command>
    aliases: [gmusicrl]
    description: Plugin reload command
    permission: GMusic.Reload

permissions:
  GMusic.*:
    default: op
    description: GMusic | Permissions
    children:
      GMusic.Music: true
      GMusic.JukeBox: true
      GMusic.Disc: true
      GMusic.AdminMusic: true
      GMusic.Update: true
      GMusic.Reload: true

  GMusic.Music:
    default: true
    description: Music command | Permission

  GMusic.JukeBox:
    default: true
    description: JukeBox interaction | Permission

  GMusic.Disc:
    default: true
    description: Disc interaction | Permission

  GMusic.AdminMusic.*:
    default: op
    description: AdminMusic | Permission
    children:
      GMusic.AdminMusic: true

  GMusic.AdminMusic:
    default: op
    description: AdminMusic command | Permission

  GMusic.ByPass.*:
    default: op
    description: ByPass | Permission
    children:
      GMusic.ByPass.World: true
      GMusic.ByPass.Region: true

  GMusic.ByPass.World:
    default: op
    description: ByPass world | Permission

  GMusic.ByPass.Region:
    default: op
    description: ByPass region | Permission

  GMusic.Update:
    default: op
    description: Update notification | Permission

  GMusic.Reload:
    default: op
    description: Plugin reload command | Permission