name: ${name}
version: ${version}
description: ${description}
authors: [Gecolay]
website: https://www.spigotmc.org/resources/84004
main: ${main}
api-version: 1.18
folia-supported: true

commands:
  gmusic:
    usage: /<command> play|playing|random|stop|pause|resume|skip|toggle
    aliases: [music, gsong, song]
    description: Music command
    permission: GMusic.Music

  gadminmusic:
    usage: /<command>
    aliases: [adminmusic, gamusic, amusic, gadminsong, adminsong, gasong, asong]
    description: AMusic command
    permission: GMusic.AdminMusic

  gmusicreload:
    usage: /<command>
    aliases: [gmusicrl]
    description: Plugin reload command
    permission: GMusic.Reload

permissions:
  GMusic.*:
    default: op
    description: GMusic | Permissions
    children:
      GMusic.Music: true
      GMusic.AdminMusic: true
      GMusic.Update: true
      GMusic.Reload: true

  GMusic.Music:
    default: true
    description: Music command | Permission

  GMusic.AdminMusic.*:
    default: op
    description: AdminMusic | Permission
    children:
      GMusic.AdminMusic: true
      GMusic.AdminMusic.UseJukeBox: true

  GMusic.AdminMusic:
    default: op
    description: AdminMusic command | Permission

  GMusic.AdminMusic.UseJukeBox:
    default: op
    description: UseJukeBox | Permission

  GMusic.Update:
    default: op
    description: Update notification | Permission

  GMusic.Reload:
    default: op
    description: Plugin reload command | Permission